spring:
  application:
    name: yaboo-ec
  
  datasource:
    url: jdbc:postgresql://localhost:5432/yaboo_ec
    username: yaboo
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.yaboo.ec: DEBUG
    org.springframework.security: DEBUG